language: go
go:
- 1.14.x
dist: trusty
sudo: false
install: true
script:
- go test -v ./...
deploy:
  provider: heroku
  api_key:
    secure: FtpkkMq0RG1ssGZqvO7M2J56sNAOqxAfc/ACNu4ePC75wfX9mNo01x/ul8aPrJHJQOWpntWWgK4GcfpivzehoL0UqaRRj1W9m76/ElVY2i5oRP5Oi9/B6gOv1ICsy1dK2AIHgQv6xsGVCfr18+u6JWLEeQgF8RsNkEntjcwp3D2y/jdJdxFUuHCj+3bbcs9RGTP63mMlI6bwnx8uqscMkWPpFD+kYXxiEWJ+Ody22SXGd9/VZGsN39577bTqfpchPq7RBAmft49Tp167G5M9lfIQZ4uDSvWs+JB6kfxZOo25RtukWHBEeAiqL1KVlDO7kHOexLrTdic4zPtJXyTuGycEET9nppyBoMtgTVMChNwp4PKSkHN7gpCTuNrkFXIH1PaQQtch/z1kZ3jISPv0DNlEk9uGRxKEQdSV1yfdWIhvoe59wexgHXWSpEySk2QuWpV2NyoyS2ucUY1ff3g9NY9Jn9BqojFLyhAL3po4xO3KndGeY2QyTlZAUOq0STPhR+GaFSO9LAkLocw7V0laSy/tVvIFINSd8rUIsb0EHqiRSPcDO2kolLQu6OqyXg4jzzNiCJSdZnf0qDcI60UZfBdfHwrv+I2C4yZ76Ug5iGUhw0OekngXACNbVvylMDWkJJ1O+wEMkbCB6IK21KEIeBPN7vlH8vGdSXlDXtHDkDo=
