language: go
go:
- 1.14.x
dist: trusty
sudo: false
install: true
script:
- sh .travis/docker.sh
deploy:
  provider: heroku
  api_key:
    secure: fyaprieahnkXQltPMyrTNCPeMXAloPGPaxFvkJt0KsdZ33QzpBdh1Xv0dISZE34mKK4X6dx6NyVpZ9JwFIF5bpqE5xwtd8e4Ezozz8iDimQFApkNNckDREOQ+gYl5atyh+EnI/XF9YMjdCycQ9eyEB/BgSS90seD9C5bM01TYNgONT7XGESVCbEy21UHdeljAvX5ocd2s9AusrQkn8gVNaE5zBlUrSVAJ9j65229rFAo40AJRE9XNGDZiGOP9G/ZECr7xLOnx33JfQA4rPGDuXzh98hD9varwUVvhSrMY3Vt1GsT+uDXUrr5p5BSilgV/vxDN40VnvGXKIyEuretCErh4UTaTAP0gaR6pjvr/3yKUjWHjpRbvmKryK006GBB0l6gz04Wm2ApVRks46y7wV8EFP6JhqBm6+6iUtmo/k11qCKmFTEnIGwle+ImI/3F8C43QiCX8tvFxYMvMLYXgfnwt6Vl6dNT6MoAQKDnzaHQxmYmVPR3ue2qwDl47IvjLKsXw9v+iakLOQv8ccQikKUYnnrVjL9JHXj1ADa8HDc+Dytb4eczoo+KZGgglwWRlHXwARvX67hiXAv03Ap0H0IlKU6mnXP7z0J8ShhSFEqPiXnfq25gSzdUezHpsj2ZBedEkBFw/N1vBls50CFH5OnaiIwX9l8lP/+3gT1Vfnk=
    app: web
