language: go
go:
- 1.14.x
dist: trusty
sudo: false
install: true
script:
- go test -v ./...
deploy:
  provider: heroku
  api_key:
    secure: Gpzgyu16XdMm8q8IJ5fO1e2IStkhTKs9DDPwv864f5zDvqu8ZTS+yZlwXcaSf1a2MnMsAC55+OIdvMkVAsgvaiINaepuotmx7Ke+FwCpYHVo4Je3c9szVqVxr+y4kSWnAbsaoVtW1L/wOyj/B5ddT7/7PQ1dM9ELgTr2YUxrlu7pZ1d09CO15XJUGhe0PegnNl82kfFN9Y6yIZr5JSIlFdFa4LjdoNgG8x0T6gJrMnara5H8w71LOi72V7FJ3jDqqRqiYDRSgYTIxLV8efH5QKWqOM0BibNyBtsC2KoL5rnlnYyORfQq4I55GqHICUE57Xq2H13kz94CnWGcu+cxC82lgT9FYcS9sehapIQJwgXCKSo5i2zIRGcjRFWkyfv/XiwtV1Tl8m5iyUJj22lHRPkTzr3d1FPD+8OUXAArCj/WqL5GHIgC5Luh+Wluz3OgzUPS2ST+p/IF/iRB7x8NV7h/O4gkxwWgkopMrhBewMDEMl8L26DLpvUuCYPb6uJBz7ePGMF/yO3sUSR9UMszPinbnn58fcgxomADaz8SjMhID51nSf89ix/fo5Uz54WtvSWfuHcr4iw7J1OFBhE1mwKPSrwiC8EtOsxFz4QxwkQPtMIeyt4ySzdAy9u7q2JaAt5f4PiN48cv4RCr/HOl/Zvdc6lGuAeAJDah0e0+OEc=
