language: go
go:
- 1.14.x
dist: trusty
sudo: false
install: true
script:
- sh .travis/docker.sh
deploy:
  provider: heroku
  api_key:
    secure: ocxDxbh7acio2VpI9yYaIG3FYcDQhEqVTvwGnwfVhbI4a8NUQSXG5P4P48wCJIQRkDMkGy7G++kxcegMFlM5ORMXLAws3W5mnE2KdB8c7r+0KHIXW/pvU8IL/Fud+sQCB0xvIQPPQ5ZynBFGGYKDxxbaYG1ySKP+2Vd2wE44ok2y2O+jxfe+5wtPZV1mbi+AgvXL6+7DOiXQv+eM9z6Zf51VDp488lYQqo4R4rXn6oSdKbiy1zlrwqJpLRyKkDS8AkWzi2qT9xntobN1t4lZaOjGdtl7lTaVB2pEkd4Gnj1sKWNFtBID86nCQcOy2NXOkkNZEhVuV8gMmaPnngGxqaISTp1ZSMv7rNBqdR8S4JHhkl1Ag+jvJb0NKV6VsAUf6SAyPrl/IRTBAmhEguTfkHulfa5XQhGFu5qRz+N7pI2o7N9wbXjWLouNisdAM6l9FJvUxJPAvfdmmjAJRPzz9VSVzhpJFhd6dN6MeBkbHbZGStsVTj1c/fOhuwTWV8lFSUwyiKaQaw88QqYfrQf4HQDdMgBQL56XdPzgU5vIgrmdlADnjKtfwXgFKpBsw/UglYF0PiebJoI0G0jX1Bc3F6gmeinE9uIbN8yZ3U09KV7tSqiLHWk/WtN76t1KiT1dRg7wr3e+QlSj65dZOMU84Va8+cT3eRnAcSpXjxHo9dY=
    app: web