language: go
go:
- 1.14.x
dist: trusty
sudo: false
install: true
script:
- go test -v ./...
deploy:
  provider: heroku
  api_key:
    secure: mhG1yxKDEBEqBUJJCwg5ZQ8LehfQBGewIj55vl+FDnvOXsvD4Mvudy3QHUC83IBtxiWlsKkCCrXlOMS0XDkYU+UOlbRxIpmauDooBBJJgMJ7wCUeZf8xO5u1fCbeZ39R0hXntwtZBwBYHrPRiFMC++KLB9zcP9WH2HReC5QO+q3qH5C/WJpt4JNjQsLjt7HMKGJfknu9M95dTFAGUzRsvg08RkFOAbtxXIVwAFv3hLKqkiIgTy6i6rjItYqXlHNJlKMM2G9IHMH4aP9njvh9Tfk9LGhdT/q/LHpb2laC/0Hbvimgia+5EjrY5iBGuS+xhiBzO6J3jH1ljkxKIO0w98WF9hAbP1ow9ckej+nxuHt8av6Q7B7dTpN6l3e3IcgTCUkzIKVKnAdXbTGv1uKhhHZQTlT++wforv2m9x66kLvAXtyUqgE3SbpxUC6GCyU/G2OB960EM2PXQU5p7ieajs6V3EkA0BNR487MtLHF+dz2m7P/uSVSjDIvbPEqUzthwCEGGrHnsFwPKhGxHJp3suFN2foFzs58/yBR7rVotfuJAvCq7oe4UN3lh3pGIhB5If5Z1sEz8rt++vwHWpgTXic0Cc3wI9Z8e2ARevWhxTx9UlSN9zs2mOerTNW2jQYBcoSRRA7DSzq3pUsX+cLYjswrecUnhseJzCCLoG0TxAs=
